---
- name: Install MySQL and Utils on Debian OS Family (based on your choice in icinga2_web_ui_ido value)
  apt: name={{ item.package }}
       state=latest
  with_items: icinga2_web_ui_{{ icinga2_web_ui_ido }}_deb
  when: ansible_distribution_major_version == "7"

- name: Start MySQL
  service: name=mysql
           state=started
           enabled=yes
  when: ansible_distribution_major_version == "7"

- name: Create a Database for Icinga
  mysql_db: name={{ icinga2_web_db }}
            state=present
  register: icinga_db

- name: Import IDO Schema on Icinga Database (only once)
  mysql_db: name={{ icinga2_web_db }}
            state=import
            target={{ icinga2_ido_mysql_schema_deb }}
  when: icinga_db.changed == true

- name: Create Icinga Database User and configure Grants
  mysql_user: name={{ icinga2_web_db_dbuser }}
              password={{ icinga2_web_db_dbpass }}
              state=present
              priv="{{ icinga2_web_db_dbuser }}.*:GRANT,INSERT,SELECT,UPDATE,DELETE,DROP,CREATE VIEW,INDEX,EXECUTE"

- name: Configure Icinga2 Ido Mysql Feature
  template: src=ido-mysql.conf.j2
            dest={{ icinga2_ido_mysql_conf }}
            backup=no
            owner=nagios
            group=nagios
            mode=0640

- name: Enable Icinga2 Ido Mysql Feature
  command: "icinga2 feature enable ido-{{ icinga2_web_ui_ido }}"
  register: features_result
  changed_when: "'for these changes to take effect' in features_result.stdout"
  notify:
   - restart icinga2
