---
- name: Install https for apt (Debian)
  apt:
    name: apt-transport-https
    state: present

- name: Get Icinga2 Apt Key for Debian OS family
  apt_key:
    id: C6E319C334410682
    url: "{{ icinga2_key }}"
    state: present

  # Debmon has been shut down and is not required any more
- name: Remove Debmon Apt Key for Debian OS family (Debian)
  apt_key:
    id: DC0EE15A29D662D2
    state: absent

  # Backport repository for Debian Stretch is needed for Icinga 2.11
  # see https://icinga.com/docs/icinga2/latest/doc/02-installation/#debian-backports-repository
- name: Add backport repository for Debian Stretch
  when: ansible_distribution_release == "stretch"
  apt_repository:
    repo: "deb https://deb.debian.org/debian stretch-backports main"
    update_cache: no
    filename: "stretch-backports"
    state: present

  # The Apt repo now lives on packages.icinga.com
- name: Remove old Apt repos
  apt_repository:
    repo: "{{ item.repo|replace('packages.icinga.com', 'packages.icinga.org') }}"
    update_cache: no
    state: absent
  loop: "{{ icinga2_deb_repos }}"

- name: Get Icinga2 Apt Repos for Debian OS family
  apt_repository:
    repo: "{{ item.repo }}"
    update_cache: yes
    state: present
  loop: "{{ icinga2_deb_repos }}"

  # Debmon has been shut down and is not required any more
- name: Remove Debmon Apt Repo for Debian OS family (Debian)
  apt_repository:
    repo: "{{ icinga2_debmon_repo }}"
    update_cache: yes
    state: absent

- name: Install Icinga2 on Debian OS family
  apt:
    pkg: "{{ icinga2_pkg }}"
    update_cache: yes
    state: latest
    install_recommends: no

- name: Start Icinga2
  service:
    name: icinga2
    state: started
    enabled: yes
