---
# tasks file for icinga2-ansible-no-ui

- include: icinga2_Debian_install.yml
  when: ansible_os_family == 'Debian'

- include: icinga2_RedHat_install.yml
  when: ansible_os_family == 'RedHat'

- include: icinga2_configure.yml
  tags: icinga2_configure
