---
- name: Copy Host Definitions
  template: src=hosts_template.j2
            dest={{ icinga2_hosts_dir }}/host_{{ hostvars[item]['ansible_fqdn'] }}.conf
            owner=root 
            group=root 
            mode=0644
  with_items: groups['all']
  notify: restart icinga2
