---
- name: Install Nrpe and Plugins
  yum: name={{ item.package }} 
       state=latest
  with_items: nrpe_agent_{{ ansible_os_family }}

- name: Copy Nrpe Configuration
  template: src=nrpe.cfg.j2
            dest={{ nrpe_agent_config }}
            owner=root
            group=root
            mode=0644
            backup=yes
  notify:
   - restart nrpe
  tags:
   - nrpe_agent_config
