---
- name: Install Icinga2 IDO modules on RedHat OS family
  yum: name=icinga2-ido-mysql
       state=latest
  when: ansible_pkg_mgr == "yum"

- name: Install Icinga2 IDO modules on RedHat OS family (Fedora > 22)
  dnf: name=icinga2-ido-mysql
       state=latest
  when: ansible_pkg_mgr == "dnf"

- name: Create a IDO Database for Icinga2
  mysql_db: name={{ icinga2_db }}
            state=present
  register: icinga_ido_db

- name: Create Icinga2 IDO Database User and configure Grants
  mysql_user: name={{ icinga2_db_user }}
              password={{ icinga2_db_pass }}
              state=present
              priv="{{ icinga2_db }}.*:GRANT,INSERT,SELECT,UPDATE,DELETE,DROP,CREATE VIEW,INDEX,EXECUTE"

- name: Import the IDO Schema on Icinga Web Database (only once)
  mysql_db: name={{ icinga2_db }}
            state=import
            target={{ icinga2_web_mysql_schema_rh }}
  when: icinga_ido_db.changed == true

- name: Configure Icinga2 Ido Mysql Feature
  template: src=ido-mysql.conf.j2
            dest={{ icinga2_ido_mysql_conf }}
            backup=yes
            owner=icinga
            group=icinga
            mode=0640
  when: icinga2_ido_mysql_configuration is defined

- name: Enable Icinga2 Ido Mysql Feature
  command: "icinga2 feature enable ido-mysql"
  register: features_result
  changed_when: "'for these changes to take effect' in features_result.stdout"
  notify:
   - restart icinga2

- name: Centos Install Centos Release Scl
  package:
    name: centos-release-scl
    state: present
  when: ansible_distribution == "CentOS"

- name: RedHat Install RhScl subscription requirment
  fail:
    msg: "please enable subscription-manager repos --enable rhel-server-rhscl-{{ ansible_facts.ansible_distribution_major_version }}-rpms"
  when: ansible_distribution == "RedHat"

- name: Install Mysql php-fpm
  package:
    name: rh-php71-php-mysqlnd
    state: present
  when:
    - icinga2_ido_mysql_configuration is defined
    - ansible_distribution_major_version == "7"

- name: Install postgres php-fpm
  package:
    name: rh-php71-php-pgsql
    state: present
  when:
    - icinga2_ido_postgres_configuration is defined
    - ansible_distribution_major_version == "7"

- name: Install Mysql php-fpm
  package:
    name: rh-php70-php-mysqlnd
    state: present
  when:
    - icinga2_ido_mysql_configuration is defined
    - ansible_distribution_major_version == "6"

- name: Install postgres php-fpm
  package:
    name: rh-php70-php-pgsql
    state: present
  when:
    - icinga2_ido_postgres_configuration is defined
    - ansible_distribution_major_version == "6"


- name: Install Icinga Web2 on RedHat OS family
  yum: name={{ item }}
       state=latest
       enablerepo={{ enablerepo }}
  with_items: "{{ icinga2_web2_ui_rpm }}"
  tags: icinga2-ansible-web2-ui-install
  when: ansible_pkg_mgr == "yum"

- name: Install Icinga Web2 on RedHat OS family
  dnf: name={{ item.package }}
       state=latest
       enablerepo={{ enablerepo }}
  with_items: "{{ icinga2_web2_ui_rpm }}"
  tags: icinga2-ansible-web2-ui-install
  when: ansible_pkg_mgr == "dnf"

- name: Create a Web Database for Icinga2
  mysql_db: name={{ icinga2_web2_db }}
            state=present
  register: icinga_web_db

- name: Create Icinga2 Web Database User and configure Grants
  mysql_user: name={{ icinga2_web2_db_user }}
              password={{ icinga2_web2_db_pass }}
              state=present
              priv="{{ icinga2_web2_db }}.*:GRANT,INSERT,SELECT,UPDATE,DELETE,DROP,CREATE VIEW,INDEX,EXECUTE"

- name: Import the Web Schema on Icinga Web Database (only once)
  mysql_db: name={{ icinga2_web2_db }}
            state=import
            target={{ icinga2_web2_mysql_schema_rh }}
  when: icinga_web_db.changed == true

- name: Define web server daemon package.
  set_fact:
    web_server_daemon: "{{ __web_server_daemon_rh }}"
  when: web_server_daemon is not defined

- name: Restart {{ web_server_daemon }} and Icinga2 to Apply the Configuration
  service: name={{ item }}
           state=restarted
           enabled=yes
  with_items:
    - "{{ web_server_daemon }}"
    - icinga2
    - php-fpm
  when: ansible_pkg_mgr == "dnf"

- name: Restart {{ web_server_daemon }} and Icinga2 to Apply the Configuration
  service: name={{ item }}
           state=restarted
           enabled=yes
  with_items:
    - "{{ web_server_daemon }}"
    - icinga2
    - rh-php71-php-fpm
  when:
    - ansible_pkg_mgr == "yum"
    - ansible_distribution_major_version == "7"

- name: Restart {{ web_server_daemon }} and Icinga2 to Apply the Configuration
  service: name={{ item }}
           state=restarted
           enabled=yes
  with_items:
    - "{{ web_server_daemon }}"
    - icinga2
    - rh-php70-php-fpm
  when:
    - ansible_pkg_mgr == "yum"
    - ansible_distribution_major_version  == "6"
